"""Evidence-first plasmid annotation and characterization."""

from plasmid_oracle.api import annotate, annotate_async, plasmid
from plasmid_oracle.databases import DatabaseSetupResult, setup
from plasmid_oracle.errors import (
    InvalidLocationError,
    InvalidProviderResultError,
    InvalidSequenceError,
    InvalidSerializedPlasmidError,
    PlasmidOracleError,
    ProviderExecutionError,
    ProviderUnavailableError,
)
from plasmid_oracle.model import (
    AnalysisManifest,
    Annotation,
    AnnotationSource,
    Characterization,
    CharacterizationCall,
    EvidenceMetrics,
    Integrity,
    Location,
    Plasmid,
    ProviderRun,
    ProviderStatus,
    QualityFlag,
    ResolutionConflict,
    ResolutionStatus,
    ResolvedAnnotation,
    SequenceInfo,
    SequenceWarning,
    Span,
    Strand,
    Topology,
)
from plasmid_oracle.pipeline import (
    AnnotationProvider,
    DoctorReport,
    ProviderContext,
    ProviderDiagnostic,
    ProviderResult,
    ProviderSpec,
    doctor,
)
from plasmid_oracle.resolution import resolve_annotations
from plasmid_oracle.serialization import from_dict, from_json, to_dict, to_json

__version__ = "0.2.0a0"

__all__ = [
    "AnalysisManifest",
    "Annotation",
    "AnnotationProvider",
    "AnnotationSource",
    "Characterization",
    "CharacterizationCall",
    "DatabaseSetupResult",
    "DoctorReport",
    "EvidenceMetrics",
    "Integrity",
    "InvalidLocationError",
    "InvalidProviderResultError",
    "InvalidSerializedPlasmidError",
    "InvalidSequenceError",
    "Location",
    "Plasmid",
    "PlasmidOracleError",
    "ProviderContext",
    "ProviderDiagnostic",
    "ProviderExecutionError",
    "ProviderUnavailableError",
    "ProviderResult",
    "ProviderRun",
    "ProviderSpec",
    "ProviderStatus",
    "QualityFlag",
    "ResolutionConflict",
    "ResolutionStatus",
    "ResolvedAnnotation",
    "SequenceInfo",
    "SequenceWarning",
    "Span",
    "Strand",
    "Topology",
    "__version__",
    "annotate",
    "annotate_async",
    "doctor",
    "from_dict",
    "from_json",
    "plasmid",
    "resolve_annotations",
    "setup",
    "to_dict",
    "to_json",
]
